function [E,T,U] = autoGen_energy(q1,q2,dq1,dq2,m,I1,I2,R,g)
%AUTOGEN_ENERGY
%    [E,T,U] = AUTOGEN_ENERGY(Q1,Q2,DQ1,DQ2,M,I1,I2,R,G)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    21-Apr-2016 17:26:09

t2 = dq2.^2;
t3 = dq1.^2;
t4 = sin(q1);
t5 = I1.*t3.*(1.0./2.0);
t6 = I2.*t2.*(1.0./2.0);
t7 = cos(q1);
E = t5+t6+R.^2.*m.*(t2+q1.^2.*t3+q2.^2.*t3-q1.*q2.*t3.*2.0).*(1.0./2.0)+R.*g.*m.*(t7+q1.*t4-q2.*t4);
if nargout > 1
    t9 = q1-q2;
    t8 = R.*dq2.*t7+R.*dq1.*t4.*t9;
    t10 = R.*dq2.*t4-R.*dq1.*t7.*t9;
    T = t5+t6+m.*(t8.^2+t10.^2).*(1.0./2.0);
end
if nargout > 2
    U = g.*m.*(R.*t7+R.*t4.*t9);
end
