function [ddq1,ddq2] = autoGen_dynamics(q1,q2,dq1,dq2,m,I1,I2,R,g)
%AUTOGEN_DYNAMICS
%    [DDQ1,DDQ2] = AUTOGEN_DYNAMICS(Q1,Q2,DQ1,DQ2,M,I1,I2,R,G)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    21-Apr-2016 17:26:09

t2 = R.^2;
t3 = dq1.^2;
ddq1 = -(R.*m.*(q1-q2).*(R.*t3+g.*cos(q1)-R.*dq1.*dq2.*2.0))./(I1+m.*q1.^2.*t2+m.*q2.^2.*t2-m.*q1.*q2.*t2.*2.0);
if nargout > 1
    ddq2 = (R.*m.*(g.*sin(q1)-R.*q1.*t3+R.*q2.*t3))./(I2+m.*t2);
end
